apiVersion: batch/v1
kind: Job
metadata:
  name: countdown
spec:
  completions: 5
  ttlSecondsAfterFinished: 10
  template:
    metadata:
      name: countdown
    spec:
      containers:
        - name: counter
          image: centos:7
          command:
            - "bin/bash"
            - "-c"
            - "for i in {10..1}; do echo $i; sleep 1; done"
      restartPolicy: Never
  backoffLimit: 4